#配置jdbc数据源的相关属性
spring:
  datasource:
    url: jdbc:mysql://127.0.0.7/jpa
    username: root
    password: root
    #数据库驱动
    driver-class-name: com.mysql.jdbc.Driver

  #jpa的基本配置，参照JpaProperties
  jpa:
    hibernate:
      #定义数据表的生成策略，update代表更新或者创建数据表结构
      ddl-auto: update
    #控制台显示sql，方便观察
    show-sql: true
